services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: go_tube
      MYSQL_USER: go_user
      MYSQL_PASSWORD: go_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - go-network

  go-app:
    build: .
    container_name: go_tube_app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: go_user
      DB_PASSWORD: go_password
      DB_NAME: go_tube
    ports:
      - "8080:8080"
    networks:
      - go-network
    restart: always

networks:
  go-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local